#! /usr/bin/python
 
import string,sys
from core import *
from input import *

def main():
    E = Environment(None)

    ### First read-in builtin lisp functions
    input = Input(open("./rc.lisp","r"),E)
    while True:
        expr = input.read()
        if iserror(expr) and expr.string=='EOF':
            break
        val = lisp_eval( expr, E )
        if iserror(val):
            print "Error in builtins.lp"
            print val
            return 1

    input.close()
    input = Input(sys.stdin,E)
    print "Lispy v0.2\nPress Ctrl-D to exit."
    while True:
        try:
            expr = input.read()
            if iserror(expr) and expr.string=='EOF':
                break
            val = lisp_eval( expr, E )
            if input.input == sys.stdin:
                print val if val!=None else '()'
            if isinstance(val,Exception) and not sys.stdin.isatty():
                return 2
        except KeyboardInterrupt:
            print "\nKeyboardInterrupt"
    if input.input == sys.stdin:
        print
    input.close()

if __name__=='__main__':
    main()
